export const categories = ["Business Development Call", "Not Selling", "Creat First Appointment", "First Appointment Confirmed", "Create Second Appointment", 
"Second Appointment Confirmed", "Sign listing agrement"];

export const staticTasks = [
  {
    id: 1,
    priority: "High",
    name: "Mrs. Sarah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "3",
    value: "22 Dec, 2022",
    category: "Business Development Call",
  },
  {
    id: 2,
    priority: "Low",
    name: "Mrs. Farah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Not Selling",
  },
  {
    id: 3,
    priority: "meduim",
    name: "Mrs. Marah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Not Selling",
  },
  {
    id: 4,
    priority: "high",
    name: "Mrs. Narah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Creat First Appointment",
  },
  {
    id: 5,
    priority: "meduim",
    name: "Mrs. Narah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Creat First Appointment",
  },
  {
    id: 6,
    priority: "heigh",
    name: "Mrs. Marah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "First Appointment Confirmed",
  },
  {
    id: 7,
    priority: "heigh",
    name: "Mrs. Marah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Create Second Appointment",
  },
  {
    id: 8,
    priority: "heigh",
    name: "Mrs. Marah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Second Appointment Confirmed",
  },
  {
    id: 9,
    priority: "low",
    name: "Mrs. Marah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Second Appointment Confirmed",
  },
  {
    id: 10,
    priority: "heigh",
    name: "Mrs. Marah Williamson",
    lastupdate: "Last updated:22 Dec, 2022",
    Lastcontacted: "Last Contacted:22 Dec, 2022",
    city: "Dubai",
    Properties: "5",
    value: "22 Dec, 2022",
    category: "Sign listing agrement",
  },
  
];

